"""
Django settings for audit_logging_monitoring project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&ls$t%=sjbhho095ziow@_g65(awul1loy38ckq-ia^_m798xd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_elasticsearch_dsl',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ALLOWED_HOSTS = ['*']

env = environ.Env(
    DEBUG=(bool, False),
    NEXT_PUBLIC_BACKEND_URL=(str, "https://localhost:8000"),
    ALLOWED_HOSTS=(list, []),
    USE_X_FORWARDED_HOST=(bool, False),
    ELASTICSEARCH_APP_AUDIT_LOG_INDEX=(str, "auditlog-django-test-prod"),
    ELASTICSEARCH_APP_AUDIT_DATA_STREAM=(str, "audit-auditlog-django-test-prod"),
    ELASTICSEARCH_HOST=(str, ''),
    ELASTICSEARCH_PORT=(int, 443),
    ELASTICSEARCH_USERNAME=(str, ''),
    ELASTICSEARCH_PASSWORD=(str, ''),
    CLEAR_AUDIT_LOG_ENTRIES=(bool, True),
    ENABLE_SEND_AUDIT_LOG=(bool, True),
    DB_PREFIX=(str, ""),
    AUDIT_LOG_ORIGIN=(str, ""),
    AUDIT_TABLE_NAME=(str,"audit_logs"),
    ELASTICSEARCH_SCHEME=(str, "https"),
    DATE_TIME_PARENT_FIELD = (str, "audit_event"),
    DATE_TIME_FIELD = (str, "date_time"),
    DATABASE_URL = (str, ""),
    DATABASE_PASSWORD = (str, ""),
    DB_USE_SSL = (bool, False),
    SSL_CA = (str, ""),
    SSL_KEY = (str, ""),
    SSL_CERT = (str, ""),
    SSL_CIPHER = (str, "")
)

ELASTICSEARCH_DSL={
    "default": {
            "hosts": env("ELASTICSEARCH_HOST"),
            "use_ssl": True,
            "http_auth": (
                env("ELASTICSEARCH_USERNAME"),
                env("ELASTICSEARCH_PASSWORD"),
            )
            if env("ELASTICSEARCH_USERNAME") and env("ELASTICSEARCH_PASSWORD")
            else None,
            
        }
}

# Audit logging
AUDIT_LOG_ORIGIN = env("AUDIT_LOG_ORIGIN")
CLEAR_AUDIT_LOG_ENTRIES = env("CLEAR_AUDIT_LOG_ENTRIES")
ELASTICSEARCH_APP_AUDIT_LOG_INDEX = env("ELASTICSEARCH_APP_AUDIT_LOG_INDEX")
ELASTICSEARCH_HOST = env("ELASTICSEARCH_HOST")
ELASTICSEARCH_PORT=env("ELASTICSEARCH_PORT")
ELASTICSEARCH_APP_AUDIT_DATA_STREAM=env("ELASTICSEARCH_APP_AUDIT_DATA_STREAM")
ELASTICSEARCH_USERNAME = env("ELASTICSEARCH_USERNAME")
ELASTICSEARCH_PASSWORD = env("ELASTICSEARCH_PASSWORD")
# ENABLE_SEND_AUDIT_LOG = env("ENABLE_SEND_AUDIT_LOG")

# Field names for fetching the elastic timestamp from json data
DATE_TIME_PARENT_FIELD =  env("DATE_TIME_PARENT_FIELD")
DATE_TIME_FIELD =  env("DATE_TIME_FIELD")

# Sheme for connecting to elastic, for example: "http", or: "https"
ELASTICSEARCH_SCHEME = env("ELASTICSEARCH_SCHEME")


ROOT_URLCONF = 'audit_logging_monitoring.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'audit_logging_monitoring.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
